/**
 * Bundles src/main.ts into a single IIFE and inlines it into src/index.html.
 * Writes the result to ../assets/player.html, which is then loaded by the RN
 * PlayerScreen as a require()'d asset.
 *
 * We inline rather than ship separate JS+HTML so the WebView has zero network
 * fetches at boot — important on iOS where local file:// asset loading has
 * historically been finicky for sibling resources.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(fileURLToPath(import.meta.url))
const ENTRY = join(ROOT, 'src', 'main.ts')
const HTML_IN = join(ROOT, 'src', 'index.html')
const HTML_OUT = join(ROOT, '..', 'assets', 'player.html')
const TS_OUT = join(ROOT, '..', 'src', 'lib', 'playerHtml.ts')

const result = await Bun.build({
  entrypoints: [ENTRY],
  target: 'browser',
  format: 'iife',
  minify: true,
})

if (!result.success) {
  console.error('[player-web] bundle failed')
  for (const log of result.logs) console.error(log)
  process.exit(1)
}

const [bundle] = result.outputs
if (!bundle) {
  console.error('[player-web] no output')
  process.exit(1)
}

const js = await bundle.text()
const html = await readFile(HTML_IN, 'utf8')
const inlined = html.replace('__INLINE_JS__', () => js)

await mkdir(dirname(HTML_OUT), { recursive: true })
await writeFile(HTML_OUT, inlined, 'utf8')

// Emit a TS module exporting the HTML as a string literal. Lets the RN side
// import it with no Metro asset configuration — `<WebView source={{ html }} />`
// accepts a plain string.
const tsBody = `// AUTO-GENERATED by player-web/build.ts — do not edit.\nexport const PLAYER_HTML = ${JSON.stringify(inlined)}\n`
await mkdir(dirname(TS_OUT), { recursive: true })
await writeFile(TS_OUT, tsBody, 'utf8')

console.log(`[player-web] wrote ${HTML_OUT} (${(inlined.length / 1024).toFixed(1)} KB)`)
console.log(`[player-web] wrote ${TS_OUT}`)
